baseurl: 'https://chienfuchen32.github.io/'
languagecode: 'en-us'
title: "Jeff's note"
theme: "paige"

enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs

# Google Analytics 4
googleAnalytics: "G-LR5QZYBPT2"

menu:
  main:
  - name: Posts
    url: /posts/
  - name: Tags
    url: /tags/

paginate: 50

social:
  github: https://github.com/chienfuchen32
  gitlab: https://gitlab.com/chienfuchen32
  linkedin: https://www.linkedin.com/in/chienfuchen32

