baseURL = 'https://chienfuchen32.github.io/'
languageCode = 'en-us'
title = 'New Blog'
theme = "hyde"

# Google Analytics 4
googleAnalytics = "G-3SNCDP141D"

[params]
  description = "hello there!"
  themeColor = "theme-base-0d"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/chienfuchen32/"},
      {Name = "Tags", URL = "https://chienfuchen32.github.io/tags/"}
  ]

[taxonomies]
  category = "categories"
  tag = "tags"
